### ISSUE TITLE
shells, commands and notebooks don't seem to respect the startup_hook.sh 

### ISSUE THREAD

**Issue by zjorgensenbits** [determined-ai/determined#1584]
It would be nice if shells, commands and notebooks would automatically run the startup_hook.sh if present in the context.

**Comment by vishnu2kmohan** [comment]
@zjorgensenbits Agreed, we'll add support in a future release. I'll update this issue when it's out.

**Comment by vishnu2kmohan** [comment]
We added support for `startup-hook.sh` for notebooks and shells in [0.14.2](https://docs.determined.ai/latest/release-notes.html#version-0-14-2)

Note: We deliberately decided not to add it to commands because they are the foundation for some advanced features (e.g., Distributed Batch Inference) that will have equivalents and guidance to achieve the `startup-hook.sh` behavior, soon.

@zjorgensenbits may we please close out this issue?
