### ISSUE TITLE
Getting trial config from checkpoint

### ISSUE THREAD

**Issue by off99555** [determined-ai/determined#2696]
I have a use case where I want to grab the trial config from the checkpoint but the checkpoint only has an attribute to access experiment config.

```py
trial = client.get_trial(2663)
ckpt = trial.top_checkpoint()
cfg = ckpt.experiment_config
ctx = det.keras.TFKerasTrialContext.from_config(cfg)
model_trial = MyModelTrial(ctx)
```

The reason I want to grab the trial config is to instantiate a trial context so that I can use it to load dataset to evaluate metrics and predict again. Or use the trial to preprocess live inference dataset.
There is a work around that I currently do which is following:
```py
cfg['hyperparameters'] = ckpt.hparams
```
It works. But if there is an attribute like `ckpt.trial_config` that would definitely be better.
Or if there is a way to grab the `MyModelTrial` or `TFKerasTrialContext` directly from the checkpoint that would also be good.
Thanks.

Priority of this feature is not high but better than nothing. Excuse me if this feature already exists.

**Comment by rb-determined-ai** [comment]
Hi @off99555, we would say that a trial has an experiment config which defines a hyperparameter _space_, and a trial has a particular hyperparameter _sample_, which represents a single point in that space.  So there isn't really such thing as a "trial config".

You can in fact load a MyModelTrial directly from a checkpoint, with `ckpt.load()`, I believe.

Otherwise modifying (a copy of) the original hyperparameter config by changing its `hyperparameters` field, and creating a new experiment seems totally valid to me.  Otherwise you can also use the "continue trial" button in the webui to accomplish the same thing.

I do think there's probably some opportunity here to improve the python sdk to make continuing training a little easier, as you suggest.

**Comment by off99555** [comment]
`ckpt.load()` actually returns `<tensorflow.python.keras.engine.functional.Functional at 0x202029da520>` which is an instance of the keras model, not `MyModelTrial`.
So I cannot access the trial related functions e.g. `build_training_data_loader()` or `build_validation_data_loader()` for example.

I'm not trying to create a new experiment though. I just want to access the trial config to use it to load dataset. For example, in the trial I might set data preprocessing a certain way, so to use the model with new data, I must preprocess the data using the same method.

**Comment by rb-determined-ai** [comment]
> ckpt.load() actually returns <tensorflow.python.keras.engine.functional.Functional at 0x202029da520> which is an instance of the keras model, not MyModelTrial

Ah yes.  It's PyTorchTrial where we do that.

Then I would say overall, the way you are doing it is the way I would recommend doing it.

You could probably avoid the `ctx = ...from_config()` by pulling your dataloader functions out as helper functions, so you can call those same helper functions from either your Trial class our outside of your trial class.  But that's up to you.

**Comment by off99555** [comment]
So is there a plan
