### ISSUE TITLE
build: refine where we generate and persist API bindings

### ISSUE THREAD

**Issue by hamidzr** [determined-ai/determined#2835]
https://determined-community.slack.com/archives/C025A98H82X/p1628812241031100

**Comment by hamidzr** [comment]
TODO update the error message that pops up present more details

**Comment by hamidzr** [comment]
what do you think about `build-bindings` target to also create a commit for you if it results in a change?

**Comment by ioga** [comment]
I don't think this is necessary when you run things locally: you may be in the middle of development, and thus you may have other dirty changes in the repo. it will complicate things. 
Running `git add -u` and `git commit -m wip` is already trivial enough.

**Comment by hamidzr** [comment]
print all or part of the diff that was expected to be included as part of the error message.

**Comment by ioga** [comment]
I think my original problem was more along the lines of "I forgot we need to do that, and I don't even remember *how* to do that". Once you know that, the process is straightforward.

When we had the obscure go.sum/go.mod issues between local or CI, the diff could've been helpful because it's hard to tell what's wrong and you're debugging it. With these bindings luckily this is not a case, AFAIK.

**Comment by hamidzr** [comment]
@ioga  https://github.com/determined-ai/determined/pull/3361 addresses this issue as well. lmk if you think we should do more.
