### ISSUE TITLE
 Performance issues in the program

### ISSUE THREAD

**Issue by DLPerf** [determined-ai/determined#2843]
Hello,I found a performance issue in the definition of `xor_input_fn` ,
[dataset = dataset.map(map_dataset)](https://github.com/determined-ai/determined/blob/b7c88380a4fe44c88bdda4d8c8180715443bc9b8/harness/tests/experiment/fixtures/estimator_xor_model.py#L26) was called without **num_parallel_calls**.
I think it will increase the efficiency of your program if you add this.

The same issues also exist in [dataset = dataset.map(parse_mnist_tfrecord)](https://github.com/determined-ai/determined/blob/b7c88380a4fe44c88bdda4d8c8180715443bc9b8/examples/computer_vision/mnist_estimator/model_def.py#L111)

Here is [the documemtation of tensorflow](https://tensorflow.google.cn/api_docs/python/tf/data/Dataset?hl=en#map) to support this thing.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by vishnu2kmohan** [comment]
Hi @DLPerf - thanks for the report, and suggestion! 

Out of curiosity, by bow much does performance improve - i.e., before and after the fix?

We'd _love_ if you would contribute a PR to fix this (and not because we're too busy, but because we'd love to encourage more contributions from the community).

**Comment by DLPerf** [comment]
Ok,I am willing to offer you my PR.I just want to know if you could offer me a benchmark .
Anyway,it would be more convient.
