### ISSUE TITLE
int search range is not inclusive of maxval

### ISSUE THREAD

**Issue by off99555** [determined-ai/determined#2844]
I suspect that the search range is in inclusive of minval but it's not inclusive of maxval.
So from the following config, only 1,2,3 will be sampled.
```yaml
  n_blocks:
    type: int
    minval: 1
    maxval: 4
```

Now the catch is that the sampling will work properly (include maxval) when testing using `determined.keras.TFKerasTrialContext.from_config(cfg)`.
But it will not work properly when deployed as an experiment. (I run on AWS)

I tried to find one of the trial that has `n_blocks=4` from the web UI and I cannot find it so I suspect that it doesn't include maxval. I haven't proven it though because I don't know which line of determined code is responsible for sampling in the cloud.

**Comment by vishnu2kmohan** [comment]
Thanks for the report @off99555, we'll look into this...

**Comment by rb-determined-ai** [comment]
Bug fix is [ready](https://github.com/determined-ai/determined/pull/2884), but since it will break reproducibility for hyperparameter selection (not for the training, just the hparam selection), we're not going to land it until v0.17.0 (which is expected in a couple of weeks).

Thank you for reporting this, @off99555!
