### ISSUE TITLE
Determined does not build on Python 3.9 due to TensorFlow 2.4.3 dependency in e2e_tests/tests/requirements.txt

### ISSUE THREAD

**Issue by sirredbeard** [determined-ai/determined#4480]
**Summary**

The [Installation from Source guide](https://github.com/determined-ai/determined/blob/master/CONTRIBUTING.md#installation-from-source) in [CONTRIBUTING.md](https://github.com/determined-ai/determined/blob/master/CONTRIBUTING.md) states that Python `<= 3.9` is supported, however `e2e_tests/tests/requirements.txt` requires `tensorflow==2.4.3` which is not available for Python 3.9.

Python 3.9:

![image](https://user-images.githubusercontent.com/33820650/177402727-2199b81b-9c73-4a7e-a9a2-0cbcb2f2bd21.png)

Python 3.8:

```
(determined) hayden@T730:~/determined$ python3.8 --version
Python 3.8.13
(determined) hayden@T730:~/determined$ make all
make get-deps
make[1]: Entering directory '/home/hayden/determined'
....
Collecting tensorflow==2.4.3
  Downloading tensorflow-2.4.3-cp38-cp38-manylinux2010_x86_64.whl (394.6 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 394.6/394.6 MB 7.6 MB/s eta 0:00:00
```

**Expected Results**

Because the guide states Python 3.9 is supported, that Determined would build on Python 3.9.

**Actual Results**

Because TensorFlow 2.4.3 is not available for Python 3.9, the Determined build fails.

**Possible Solutions**

* Update the version of TensorFlow in `e2e_tests/tests/requirements.txt` to a version supported by Python 3.9.
* Change the guide to state Python `< 3.9` because 3.9 and + is not supported.

**Comment by ioga** [comment]
Hi Hayden,

`determined` python package itself doesn't [depend](https://github.com/determined-ai/determined/blob/master/harness/setup.py#L17) on tensorflow at all, and doesn't restrict its versions, because tensorflow version is usually the user's choice. But we do officially support 1.15 as well as 2.4-2.8. 2.8 is the one we ship by "default" in the environment images. 

I expect 2.9 may work as well, but we haven't had time to test this out yet. These versions have their own python requirements, but we should support everything between python 3.7 and 3.9.

tensorflow 2.4.3 is pinned in `e2e_tests/tests/requirements.txt` primarily for our e2e testing, to make the CI more predictable and more consistent with local developer setups. it runs on circleci intregration you can see on the github repo, and it uses python 3.7. this pin doesn't affect end-users.

A good solution here is to upgrade the TF version in `e2e_tests/tests/requirements.txt` to the latest one in 2.8.x branch to make it in line with the default TF version. It also supports 3.9 which would address your concern. This upgrade has been on the internal roadmap for some time now, but we haven't had resources to do this just yet.

**Comment by sirredbeard** [comment]
Thank you for your response, @ioga! 

`this pin doesn't affect end-users`

But this pin does affect users trying to follow the build guide.

`This upgrade has been on the internal roadmap for some time now`

Could we notate something on the build guide in the meantime?

**Comment by sirredbeard** [comment]
This can be notated in the Installation from Source guide. Closing in favor of #4481.
