### ISSUE TITLE
🤔[question] Fluentbit container not launched in task container defaults network_mode

### ISSUE THREAD

**Issue by obonyojimmy** [determined-ai/determined#5070]
### Describe your question

Fluentbit container started by agents , do not get launched in specified `network_mode` whilst other tasks containers (tensorboard, notebooks ...etc)  get deployed correctly in the `network_mode` .

**Comment by ighodgao** [comment]
Hi @obonyojimmy, thanks for your question! We'll get back to you as soon as possible.

**Comment by rb-determined-ai** [comment]
Hi @obonyojimmy, sorry for the delay.

I had to go look this one up.

You are correct, we always run the fluentbit container in host networking mode, since it's actually the docker daemon itself that talks to the fluentbit container, not anything inside the containers.

Is that not meeting your needs for some reason?

**Comment by obonyojimmy** [comment]
Thanks  @rb-determined-ai , for quick response , that solves my question .
