### ISSUE TITLE
Pytorch Lightning v1.7.7 support

### ISSUE THREAD

**Issue by benjaminrwilson** [determined-ai/determined#5149]
### Describe your question

Hi,

Thank you for the great work! How difficult would be bumping `pytorch_lightning` to v1.7.7 (#5111)?

This would be quite helpful.

Thanks!

**Comment by rb-determined-ai** [comment]
This isn't very high priority for us right now.

Part of the reason is that our current PTL support hooks into some of the internals of PTL.  Those internals are pretty unstable and actually supporting new versions is quite a bit of work for us.

Another part of the reason is that we have a new vision for the PTL support we would like to provide, and it involves supporting PTL at the `Trainer` level rather than at the `LightningModule` level.  We think that will be more stable for us to maintain and also a much better experience for end-users.  That work is a little down the road, as we're prioritizing a newer integration with Keras first.
