### ISSUE TITLE
The key(min_checkpoint_period) in yaml  file seems to have some error 🤔[question] 

### ISSUE THREAD

**Issue by caiduoduo12138** [determined-ai/determined#5643]
### Describe your question
<pre>
I set the key(min_checkpoint_period) as：
   min_checkpoint_period:
     epochs: 2
But the checkpoints do not save at each 2 epochs.
<pre/>
l am sorry for my poor English. If possible, can you give me some advice.

**Comment by caiduoduo12138** [comment]
![1](https://user-images.githubusercontent.com/55495912/209109492-203ab0b3-90b0-4195-824f-b0c34ed19064.png)

**Comment by ioga** [comment]
hello,

what is your `records_per_epoch` and batch size? I recall you had [issue](https://github.com/determined-ai/determined/issues/5564) with that previously. assuming the first column in your screenshot is batches, it seems like you have about 7 batches per epoch.

also, in general, when you screenshot a table, it'd be helpful to screenshot it in the way we could tell which table it is, e.g. include page or table headers. otherwise it's hard for us to tell what these sheet of numbers is.

**Comment by caiduoduo12138** [comment]
![C6W(9R J 7C)VBN$05{QK~2](https://user-images.githubusercontent.com/55495912/209251619-c5535c76-57b8-4f14-be10-dde14bb698a8.png)
I create a new experiment(total 50 epoch and save at 10 each epcoh) and the yaml is below:
![2](https://user-images.githubusercontent.com/55495912/209252237-5531f769-3ecf-47f0-a249-19589cb1df94.png)
I think that the batches on one epoch can be computed as  **records_per_epoch** / **global_batch_size**.

**Comment by ioga** [comment]
In this case, you only see two checkpoints because the checkpoint garbage collector did its job. Here are the [configuration docs](https://docs.determined.ai/latest/reference/reference-training/experiment-config-reference.html?highlight=save_trial_best#checkpoint-garbage-collection)
Two remaining checkpoints are the one with best `validation_loss` (batch 98), and the other one is the latest (batch 734).

If you want to effectively disable garbage collector and preserve all checkpoints for whatever reason, you could set `checkpoint_storage -> save_trial_latest` in your experiment config to some very large number, e.g. 
```
checkpoint_storage:
  save_trial_latest: 100000
```

**Comment by caiduoduo12138** [comment]
Thanks for your advice!
