### ISSUE TITLE
PyTorchTrialContext method .from_config() deprecated?

### ISSUE THREAD

**Issue by jakefleisig** [determined-ai/determined#6866]
in the previous version of determined there was a method of `PyTorchTrialContext` called `.from_config()` .  it seems as if thats been deprecated, but this was useful for loading in the config args from a yaml into a notebook in order to debug a determined trial:
```
with open('./myconfig.yaml') as f:
    config = yaml.safe_load(f)
# create my trial
context = PyTorchTrialContext.from_config(config)
Trial = MyTrial(context)
```
does anyone know what the replacement of this method is now called? or if it exists still?

**Comment by azhou-determined** [comment]
This was removed in 0.21.0 when we introduced [Trainer API for PyTorch](https://docs.determined.ai/latest/training/apis-howto/api-pytorch-ug.html#pytorch-trainer). It includes by design a method to instantiate a `PyTorchTrialContext` which is more powerful than the previous `PyTorchTrialContext.from_config()`. 

The replacement of the deprecated method using PyTorch Trainer:
```
with open("./config.yaml") as f:
         config = yaml.safe_load(f)

# pass in experiment config here
with det.pytorch.init(exp_conf=config) as train_context:
        trial = MyTrial(train_context)
```
Depending on what you are trying to debug, you could also pass arguments directly into your `PyTorchTrial` and use them directly in the trial instead of reading from the context object:
```
with open("./config.yaml") as f:
         config = yaml.safe_load(f)

with det.pytorch.init() as train_context:
        # pass in whatever arguments you need in your trial
        trial = MyTrial(train_context, config)
...
class MyTrial:
        def __init__(context, config):
                self.config = config
```

**Comment by jakefleisig** [comment]
this is great, thank you! had to modify slightly:
```
with open("./config.yaml") as f:
     config = yaml.safe_load(f)

# pass in experiment config here
with det.pytorch.init(exp_conf=config, hparams=config['hyperparameters']) as train_context:
    trial = MyTrial(train_context)
```
but this works now!
