### ISSUE TITLE
🤔[question] llama2 test: AttributeError: 'str' object has no attribute 'type'

### ISSUE THREAD

**Issue by caiduoduo12138** [determined-ai/determined#7746]
### Describe your question

env: determined 0.24.0
image: determinedai/environments:cuda-11.8-pytorch-2.0-gpu-mpi-0.24.0

I build a script about llama2 and try to create multinodes task. Can you give me some help. Here are code and log:
[model_def.txt](https://github.com/determined-ai/determined/files/12451292/model_def.txt)
[distributed.txt](https://github.com/determined-ai/determined/files/12451294/distributed.txt)
[experiment_66_trial_64_logs.txt](https://github.com/determined-ai/determined/files/12451299/experiment_66_trial_64_logs.txt)

**Comment by KevinMusgrave** [comment]
It seems like one of the model's `state_dict` values is a string instead of a tensor.

Can you add the following snippet of code after `self.model = self.context.wrap_model(model)` and paste the output here?

```python
        for k,v in self.model.state_dict().items():
            print(k, type(v))
```

**Comment by ioga** [comment]
Correct me if I am wrong, but I believe the llama2 model code needs torch FSDP, e.g. your code imports some pieces FSDP and does not use these, but I assume it was used in the original. 

Our `PyTorchTrial` API uses horovod by default (which wraps your code with horovod `DistributedOptimizer`), and we also support [torch distributed](https://docs.determined.ai/latest/model-dev-guide/submit-experiment.html#pytorch-distributed-launcher) which wraps your code in `torch.nn.parallel.DistributedDataParallel`. `PyTorchTrial` doesn't have first-class support for FSDP.

I am worried that porting this code from FSDP to horovod could be an uphill battle. I'd suggest trying our [the torch distributed launcher](https://docs.determined.ai/latest/model-dev-guide/submit-experiment.html#configure-a-launcher) instead first because torch DDP is closer to FSDP. See any code which has `entrypoint: python3 -m determined.launch.torch_distributed` in the expconf as an example.

If that does not work, our training loops probably cannot be used here, but you can still use [Core API](https://docs.determined.ai/latest/model-dev-guide/apis-howto/api-core-ug.html#core-api-user-guide) for lower-level hp tuning or metrics training support.

**Comment by caiduoduo12138** [comment]
thank you, I will try it and answer you later

**Comment by liamcli** [comment]
Here's an example for how to finetune vicuna v1.5 (finetuned llama 2) using our core api with hf trainer.
[hf_lora.zip](https://github.com/determined-ai/determined/files/12489513/hf_lora.zip)

**Comment by caiduoduo12138** [comment]
> Here's an example for how to finetune vicuna v1.5 (finetuned llama 2) using our core api with hf trainer. [hf_lora.zip](https://github.com/determined-ai/determined/files/12489513/hf_lora.zip)
