### ISSUE TITLE
Does Determined AI support below features?🤔[question] 

### ISSUE THREAD

**Issue by humbleearth** [determined-ai/determined#8331]
### Describe your question

1. Explainability of inference predictions
2. Drift detection with built in determined ai algorithms or use of external algorithms in the platform
3. ONNX support for optimized model conversion
4. Integration with Grafana / ELK dashboard
5. A/B, canary, blue/green etc deployment
6. Support for delta uploads - means if some data was previously used, if new data comes is it able to detect the delta and use it along with the original data instead of uploading and using the whole data.
7. Data labelling, text labelling or if not inclusion of external vendor data labelling tools into the platform

### Checklist

- [X] Did you search [the docs](https://docs.determined.ai/latest/) for a solution?
- [X] Did you search github issues to find if somebody asked this question before?

**Comment by ioga** [comment]
hello,

1. no
2. no
3. no built-in magic for this either, our users typically do it themselves because it's sufficiently simple.
4. We support prometheus/grafana for the hardware monitoring: https://docs.determined.ai/latest/integrations/prometheus/_index.html#prometheus-grafana . As for ELK, we have a [logging backend for ElasticSearch](https://docs.determined.ai/latest/manage/elasticsearch-logging-backend.html), but it's considered legacy, and we do not recommend it.
5. Some of our users run separate independent staging & prod environments, and update the staging first to validate the upgrades.
6. We have a sister product called [pachyderm](https://github.com/pachyderm/pachyderm) which does exactly that.
7. We are not prescriptive about data loading or data management. You are free to use external tools and store you data any way you see fit.

**Comment by humbleearth** [comment]
ioga I understand when you say users run separate environments, they are not part of determined ai and as such determined does not provide any custom plugability or integration to the core framework for such changes or requriements.

**Comment by ioga** [comment]
Running separate environments means installing multiple clusters. if these were somehow integrated together, something could go wrong in the integration layer making it a single point of failure. Independent setup allows for a smaller blast radius.

**Comment by hkumar92** [comment]
Hi @humbleearth, thanks for the useful feedback. Would you be open to a chat about this so we can dive deeper into what you're trying to do and where we can help? You can find me on the [determined community slack](https://determined-community.slack.com/), as haran.determined. Looking forward to chatting!
