### ISSUE TITLE
cat I change the save path of checkpoint on master node?🤔[question] 

### ISSUE THREAD

**Issue by ghuorahgaorhga** [determined-ai/determined#8368]
### Describe your question

it seems save at /tmp/determined-checkpoint/
I want to save checkpoints at /data/temp/determined-checkpoint/

### Checklist

- [X] Did you search [the docs](https://docs.determined.ai/latest/) for a solution?
- [X] Did you search github issues to find if somebody asked this question before?

**Comment by rb-determined-ai** [comment]
See docs: https://docs.determined.ai/latest/reference/deploy/master-config-reference.html#checkpoint-storage

If you are using /tmp/determined-checkpoint, you are likely using `det deploy local cluster-up`, in which case you'll need to set `--master-config-path` in order to use the master yaml described in the docs.

**Comment by ghuorahgaorhga** [comment]
which type of
