### ISSUE TITLE
DDMScheduler parameter bug 

### ISSUE THREAD

**Issue by paulaserna16** [determined-ai/determined#8392]
### Describe the bug

When running the **_textual_inversion_stable_diffusion_** example, I get this error:

TypeError: __init__() got an unexpected keyword argument 'tensor_format'

### Reproduction Steps

1. Go to trainer.py
2. Go to build_train_scheduler()
3. Delete tensor='pt' parameter

def _build_train_scheduler(self) -> None:
        self.train_scheduler = DDPMScheduler(
            beta_start=self.beta_start,
            beta_end=self.beta_end,
            beta_schedule="scaled_linear",
            num_train_timesteps=self.num_train_timesteps,
        )

### Expected Behavior

It will work without any issue.

### Screenshot

It will work

### Environment

- Device or hardware: [e.g. iPhone6, Nvidia A100]

### Additional Context

DDPMScheduler doesn't have any parameter called tensor_format as input.

**Comment by rb-determined-ai** [comment]
Thanks for the report, we'll get somebody to either clarify what's going on or to fix the example to be up-to-date.  Right now the author of that example happens to be on vacation.

**Comment by garrett361** [comment]
Hmm, yeah the `tensor_format` argument [was deprecated](https://github.com/huggingface/diffusers/pull/651/files) right around when this example was released. The example hard-codes diffusers `0.5.1` in [startup-hook.sh](https://github.com/determined-ai/determined/blob/main/examples/diffusion/textual_inversion_stable_diffusion/startup-hook.sh), though, and the code should run fine as is, since in  `0.5.1` there is still just a [deprecation warning.](https://github.com/huggingface/diffusers/blob/0679d090837ed6e67b73d64ec1bdc05ef832a140/src/diffusers/schedulers/scheduling_ddpm.py#L117-L122).  I just ran the `finetune_cont.yaml` experiment as-is on an A100 node and it trained without issue.

Did you update any dependencies before running the code? This example is a bit outdated now, on ML timescales and could use an update.
