### ISSUE TITLE
🐛Update readme for @hpe.com/glide-data-grid and consider contributing back

### ISSUE THREAD

**Issue by jassmith** [determined-ai/determined#8617]
### Describe the bug

Hello team! Thank you so much for adopting GDG. I have received freedback in other channels that some users are accidentally installed the @hpe.com fork of GDG thinking it is the main package. Would you be willing to update the readme so in npmjs it shows as a fork or is otherwise clear to the user this is not the package they are looking for?

While I got you here, I'd love to know what I can bring back to resolve the fork in general.

### Reproduction Steps

1. Go here https://www.npmjs.com/package/@hpe.com/glide-data-grid
2. Read the readme

### Expected Behavior

It should make it clear that this is a fork.

### Screenshot

N/A

### Environment

N/A

**Comment by mapmeld** [comment]
I've updated the README on NPM and GitHub so it'll be clear that it's a fork.
We'll revisit the possibility of describing our changes and contributing back in Jan 2024

**Comment by jassmith** [comment]
I really appreciate the prompt response. Especially considering how close to christmas we are.

**Comment by jassmith** [comment]
Can you explain the intent of this diff maybe? https://github.com/glideapps/glide-data-grid/commit/4c94ecd57fdee36c1eee24a26e67c69d57bade90?diff=split&w=0

I see the message but I cannot see how the diff enables that.

**Comment by mapmeld** [comment]
I think the issue there is `defaultSize` (150px) is returned for the width for any `GridCellKind.Custom` , instead of allowing these types to call `r?.measure?`. Should they be overriding something else?
I'm getting more info about the other line there, if we have any reason to expect a 0 width which we override using `||` instead of `??` there.

Doing the diff, the only other changes are resizing columns https://github.com/determined-ai/glide-data-grid/pull/3 and middle mouse button check https://github.com/determined-ai/glide-data-grid/commit/ab22e79aa95a14c0b71fa8ae328fb9bee57b16b5

**Comment by jassmith** [comment]
The last 2 you mentioned are already taken back to the mainline branch. The one in question I see the problem with. I will get a fix in ASAP.

**Comment by jassmith** [comment]
I've validated that the defaultSize is not an issue in the 6.0.0 series. You should be able to move back to the stable mainline. There is a release candidate available now as 5.99.9-rc2 right now.

**Comment by mapmeld** [comment]
Thanks! I've opened a PR to upgrade to 6.0.0, so closing this issue.
